#include <gtkmm.h>
#include "Control.h"

int main(int argCount, char *argv[]) {
    auto app = Gtk::Application::create(argCount, argv, "de.oerntec.desktopcropper");

    Glib::RefPtr<Gtk::Builder> builder = Gtk::Builder::create_from_string("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                                                                                  "<!-- Generated with glade 3.18.3 -->\n"
                                                                                  "<interface>\n"
                                                                                  "  <requires lib=\"gtk+\" version=\"3.12\"/>\n"
                                                                                  "  <object class=\"GtkApplicationWindow\" id=\"main_window\">\n"
                                                                                  "    <property name=\"can_focus\">False</property>\n"
                                                                                  "    <property name=\"default_width\">1920</property>\n"
                                                                                  "    <property name=\"default_height\">1080</property>\n"
                                                                                  "    <child>\n"
                                                                                  "      <object class=\"GtkPaned\" id=\"main_pane\">\n"
                                                                                  "        <property name=\"visible\">True</property>\n"
                                                                                  "        <property name=\"can_focus\">True</property>\n"
                                                                                  "        <property name=\"wide_handle\">True</property>\n"
                                                                                  "        <child>\n"
                                                                                  "          <object class=\"GtkBox\" id=\"box\">\n"
                                                                                  "            <property name=\"width_request\">500</property>\n"
                                                                                  "            <property name=\"visible\">True</property>\n"
                                                                                  "            <property name=\"can_focus\">False</property>\n"
                                                                                  "            <property name=\"orientation\">vertical</property>\n"
                                                                                  "            <child>\n"
                                                                                  "              <object class=\"GtkMenuBar\" id=\"menubar1\">\n"
                                                                                  "                <property name=\"visible\">True</property>\n"
                                                                                  "                <property name=\"can_focus\">False</property>\n"
                                                                                  "                <child>\n"
                                                                                  "                  <object class=\"GtkMenuItem\" id=\"menuitem1\">\n"
                                                                                  "                    <property name=\"visible\">True</property>\n"
                                                                                  "                    <property name=\"can_focus\">False</property>\n"
                                                                                  "                    <property name=\"label\" translatable=\"yes\">_File</property>\n"
                                                                                  "                    <property name=\"use_underline\">True</property>\n"
                                                                                  "                    <child type=\"submenu\">\n"
                                                                                  "                      <object class=\"GtkMenu\" id=\"menu1\">\n"
                                                                                  "                        <property name=\"visible\">True</property>\n"
                                                                                  "                        <property name=\"can_focus\">False</property>\n"
                                                                                  "                        <child>\n"
                                                                                  "                          <object class=\"GtkImageMenuItem\" id=\"menu_save\">\n"
                                                                                  "                            <property name=\"label\">gtk-save</property>\n"
                                                                                  "                            <property name=\"visible\">True</property>\n"
                                                                                  "                            <property name=\"can_focus\">False</property>\n"
                                                                                  "                            <property name=\"use_underline\">True</property>\n"
                                                                                  "                            <property name=\"use_stock\">True</property>\n"
                                                                                  "                          </object>\n"
                                                                                  "                        </child>\n"
                                                                                  "                        <child>\n"
                                                                                  "                          <object class=\"GtkImageMenuItem\" id=\"menu_open\">\n"
                                                                                  "                            <property name=\"label\">gtk-open</property>\n"
                                                                                  "                            <property name=\"visible\">True</property>\n"
                                                                                  "                            <property name=\"can_focus\">False</property>\n"
                                                                                  "                            <property name=\"use_underline\">True</property>\n"
                                                                                  "                            <property name=\"use_stock\">True</property>\n"
                                                                                  "                          </object>\n"
                                                                                  "                        </child>\n"
                                                                                  "                        <child>\n"
                                                                                  "                          <object class=\"GtkImageMenuItem\" id=\"menu_save_as\">\n"
                                                                                  "                            <property name=\"label\">gtk-save-as</property>\n"
                                                                                  "                            <property name=\"visible\">True</property>\n"
                                                                                  "                            <property name=\"can_focus\">False</property>\n"
                                                                                  "                            <property name=\"use_underline\">True</property>\n"
                                                                                  "                            <property name=\"use_stock\">True</property>\n"
                                                                                  "                          </object>\n"
                                                                                  "                        </child>\n"
                                                                                  "                      </object>\n"
                                                                                  "                    </child>\n"
                                                                                  "                  </object>\n"
                                                                                  "                </child>\n"
                                                                                  "              </object>\n"
                                                                                  "              <packing>\n"
                                                                                  "                <property name=\"expand\">False</property>\n"
                                                                                  "                <property name=\"fill\">True</property>\n"
                                                                                  "                <property name=\"position\">0</property>\n"
                                                                                  "              </packing>\n"
                                                                                  "            </child>\n"
                                                                                  "            <child>\n"
                                                                                  "              <object class=\"GtkLabel\" id=\"scale_warning_label\">\n"
                                                                                  "                <property name=\"visible\">True</property>\n"
                                                                                  "                <property name=\"can_focus\">False</property>\n"
                                                                                  "                <property name=\"label\" translatable=\"yes\">label</property>\n"
                                                                                  "                <property name=\"lines\">1</property>\n"
                                                                                  "              </object>\n"
                                                                                  "              <packing>\n"
                                                                                  "                <property name=\"expand\">False</property>\n"
                                                                                  "                <property name=\"fill\">True</property>\n"
                                                                                  "                <property name=\"position\">3</property>\n"
                                                                                  "              </packing>\n"
                                                                                  "            </child>\n"
                                                                                  "            <child>\n"
                                                                                  "              <object class=\"GtkBox\" id=\"box5\">\n"
                                                                                  "                <property name=\"visible\">True</property>\n"
                                                                                  "                <property name=\"can_focus\">False</property>\n"
                                                                                  "                <property name=\"orientation\">vertical</property>\n"
                                                                                  "                <child>\n"
                                                                                  "                  <object class=\"GtkLabel\" id=\"label1\">\n"
                                                                                  "                    <property name=\"visible\">True</property>\n"
                                                                                  "                    <property name=\"can_focus\">False</property>\n"
                                                                                  "                    <property name=\"label\" translatable=\"yes\">Image scale factor</property>\n"
                                                                                  "                  </object>\n"
                                                                                  "                  <packing>\n"
                                                                                  "                    <property name=\"expand\">False</property>\n"
                                                                                  "                    <property name=\"fill\">True</property>\n"
                                                                                  "                    <property name=\"position\">0</property>\n"
                                                                                  "                  </packing>\n"
                                                                                  "                </child>\n"
                                                                                  "                <child>\n"
                                                                                  "                  <object class=\"GtkBox\" id=\"box1\">\n"
                                                                                  "                    <property name=\"visible\">True</property>\n"
                                                                                  "                    <property name=\"can_focus\">False</property>\n"
                                                                                  "                    <child>\n"
                                                                                  "                      <object class=\"GtkScale\" id=\"scale_image\">\n"
                                                                                  "                        <property name=\"visible\">True</property>\n"
                                                                                  "                        <property name=\"can_focus\">True</property>\n"
                                                                                  "                        <property name=\"draw_value\">False</property>\n"
                                                                                  "                      </object>\n"
                                                                                  "                      <packing>\n"
                                                                                  "                        <property name=\"expand\">True</property>\n"
                                                                                  "                        <property name=\"fill\">True</property>\n"
                                                                                  "                        <property name=\"position\">1</property>\n"
                                                                                  "                      </packing>\n"
                                                                                  "                    </child>\n"
                                                                                  "                    <child>\n"
                                                                                  "                      <object class=\"GtkSpinButton\" id=\"image_scale_spin_button\">\n"
                                                                                  "                        <property name=\"visible\">True</property>\n"
                                                                                  "                        <property name=\"can_focus\">True</property>\n"
                                                                                  "                        <property name=\"text\" translatable=\"yes\">0,0000000000</property>\n"
                                                                                  "                        <property name=\"digits\">10</property>\n"
                                                                                  "                      </object>\n"
                                                                                  "                      <packing>\n"
                                                                                  "                        <property name=\"expand\">False</property>\n"
                                                                                  "                        <property name=\"fill\">True</property>\n"
                                                                                  "                        <property name=\"position\">2</property>\n"
                                                                                  "                      </packing>\n"
                                                                                  "                    </child>\n"
                                                                                  "                  </object>\n"
                                                                                  "                  <packing>\n"
                                                                                  "                    <property name=\"expand\">False</property>\n"
                                                                                  "                    <property name=\"fill\">True</property>\n"
                                                                                  "                    <property name=\"position\">1</property>\n"
                                                                                  "                  </packing>\n"
                                                                                  "                </child>\n"
                                                                                  "              </object>\n"
                                                                                  "              <packing>\n"
                                                                                  "                <property name=\"expand\">False</property>\n"
                                                                                  "                <property name=\"fill\">True</property>\n"
                                                                                  "                <property name=\"position\">6</property>\n"
                                                                                  "              </packing>\n"
                                                                                  "            </child>\n"
                                                                                  "            <child>\n"
                                                                                  "              <object class=\"GtkBox\" id=\"box6\">\n"
                                                                                  "                <property name=\"visible\">True</property>\n"
                                                                                  "                <property name=\"can_focus\">False</property>\n"
                                                                                  "                <property name=\"orientation\">vertical</property>\n"
                                                                                  "                <child>\n"
                                                                                  "                  <object class=\"GtkLabel\" id=\"label2\">\n"
                                                                                  "                    <property name=\"visible\">True</property>\n"
                                                                                  "                    <property name=\"can_focus\">False</property>\n"
                                                                                  "                    <property name=\"label\" translatable=\"yes\">monitor scale factor</property>\n"
                                                                                  "                  </object>\n"
                                                                                  "                  <packing>\n"
                                                                                  "                    <property name=\"expand\">False</property>\n"
                                                                                  "                    <property name=\"fill\">True</property>\n"
                                                                                  "                    <property name=\"position\">0</property>\n"
                                                                                  "                  </packing>\n"
                                                                                  "                </child>\n"
                                                                                  "                <child>\n"
                                                                                  "                  <object class=\"GtkBox\" id=\"box2\">\n"
                                                                                  "                    <property name=\"visible\">True</property>\n"
                                                                                  "                    <property name=\"can_focus\">False</property>\n"
                                                                                  "                    <child>\n"
                                                                                  "                      <object class=\"GtkScale\" id=\"scale_monitors\">\n"
                                                                                  "                        <property name=\"visible\">True</property>\n"
                                                                                  "                        <property name=\"can_focus\">True</property>\n"
                                                                                  "                        <property name=\"draw_value\">False</property>\n"
                                                                                  "                      </object>\n"
                                                                                  "                      <packing>\n"
                                                                                  "                        <property name=\"expand\">True</property>\n"
                                                                                  "                        <property name=\"fill\">True</property>\n"
                                                                                  "                        <property name=\"position\">1</property>\n"
                                                                                  "                      </packing>\n"
                                                                                  "                    </child>\n"
                                                                                  "                    <child>\n"
                                                                                  "                      <object class=\"GtkSpinButton\" id=\"monitor_scale_spin_button\">\n"
                                                                                  "                        <property name=\"visible\">True</property>\n"
                                                                                  "                        <property name=\"can_focus\">True</property>\n"
                                                                                  "                        <property name=\"text\" translatable=\"yes\">0,0000000000</property>\n"
                                                                                  "                        <property name=\"digits\">10</property>\n"
                                                                                  "                      </object>\n"
                                                                                  "                      <packing>\n"
                                                                                  "                        <property name=\"expand\">False</property>\n"
                                                                                  "                        <property name=\"fill\">True</property>\n"
                                                                                  "                        <property name=\"position\">2</property>\n"
                                                                                  "                      </packing>\n"
                                                                                  "                    </child>\n"
                                                                                  "                  </object>\n"
                                                                                  "                  <packing>\n"
                                                                                  "                    <property name=\"expand\">False</property>\n"
                                                                                  "                    <property name=\"fill\">True</property>\n"
                                                                                  "                    <property name=\"position\">1</property>\n"
                                                                                  "                  </packing>\n"
                                                                                  "                </child>\n"
                                                                                  "              </object>\n"
                                                                                  "              <packing>\n"
                                                                                  "                <property name=\"expand\">False</property>\n"
                                                                                  "                <property name=\"fill\">True</property>\n"
                                                                                  "                <property name=\"position\">7</property>\n"
                                                                                  "              </packing>\n"
                                                                                  "            </child>\n"
                                                                                  "            <child>\n"
                                                                                  "              <object class=\"GtkBox\" id=\"box7\">\n"
                                                                                  "                <property name=\"visible\">True</property>\n"
                                                                                  "                <property name=\"can_focus\">False</property>\n"
                                                                                  "                <property name=\"orientation\">vertical</property>\n"
                                                                                  "                <child>\n"
                                                                                  "                  <object class=\"GtkLabel\" id=\"label3\">\n"
                                                                                  "                    <property name=\"visible\">True</property>\n"
                                                                                  "                    <property name=\"can_focus\">False</property>\n"
                                                                                  "                    <property name=\"label\" translatable=\"yes\">monitor x position</property>\n"
                                                                                  "                  </object>\n"
                                                                                  "                  <packing>\n"
                                                                                  "                    <property name=\"expand\">False</property>\n"
                                                                                  "                    <property name=\"fill\">True</property>\n"
                                                                                  "                    <property name=\"position\">0</property>\n"
                                                                                  "                  </packing>\n"
                                                                                  "                </child>\n"
                                                                                  "                <child>\n"
                                                                                  "                  <object class=\"GtkBox\" id=\"box3\">\n"
                                                                                  "                    <property name=\"visible\">True</property>\n"
                                                                                  "                    <property name=\"can_focus\">False</property>\n"
                                                                                  "                    <child>\n"
                                                                                  "                      <object class=\"GtkScale\" id=\"x_monitors\">\n"
                                                                                  "                        <property name=\"visible\">True</property>\n"
                                                                                  "                        <property name=\"can_focus\">True</property>\n"
                                                                                  "                        <property name=\"restrict_to_fill_level\">False</property>\n"
                                                                                  "                        <property name=\"fill_level\">10</property>\n"
                                                                                  "                        <property name=\"draw_value\">False</property>\n"
                                                                                  "                      </object>\n"
                                                                                  "                      <packing>\n"
                                                                                  "                        <property name=\"expand\">True</property>\n"
                                                                                  "                        <property name=\"fill\">True</property>\n"
                                                                                  "                        <property name=\"position\">1</property>\n"
                                                                                  "                      </packing>\n"
                                                                                  "                    </child>\n"
                                                                                  "                    <child>\n"
                                                                                  "                      <object class=\"GtkSpinButton\" id=\"x_monitors_spin_button\">\n"
                                                                                  "                        <property name=\"visible\">True</property>\n"
                                                                                  "                        <property name=\"can_focus\">True</property>\n"
                                                                                  "                        <property name=\"text\" translatable=\"yes\">0,0000000000</property>\n"
                                                                                  "                        <property name=\"digits\">10</property>\n"
                                                                                  "                      </object>\n"
                                                                                  "                      <packing>\n"
                                                                                  "                        <property name=\"expand\">False</property>\n"
                                                                                  "                        <property name=\"fill\">True</property>\n"
                                                                                  "                        <property name=\"position\">2</property>\n"
                                                                                  "                      </packing>\n"
                                                                                  "                    </child>\n"
                                                                                  "                  </object>\n"
                                                                                  "                  <packing>\n"
                                                                                  "                    <property name=\"expand\">False</property>\n"
                                                                                  "                    <property name=\"fill\">True</property>\n"
                                                                                  "                    <property name=\"position\">1</property>\n"
                                                                                  "                  </packing>\n"
                                                                                  "                </child>\n"
                                                                                  "              </object>\n"
                                                                                  "              <packing>\n"
                                                                                  "                <property name=\"expand\">False</property>\n"
                                                                                  "                <property name=\"fill\">True</property>\n"
                                                                                  "                <property name=\"position\">8</property>\n"
                                                                                  "              </packing>\n"
                                                                                  "            </child>\n"
                                                                                  "            <child>\n"
                                                                                  "              <object class=\"GtkBox\" id=\"box8\">\n"
                                                                                  "                <property name=\"visible\">True</property>\n"
                                                                                  "                <property name=\"can_focus\">False</property>\n"
                                                                                  "                <property name=\"orientation\">vertical</property>\n"
                                                                                  "                <child>\n"
                                                                                  "                  <object class=\"GtkLabel\" id=\"label4\">\n"
                                                                                  "                    <property name=\"visible\">True</property>\n"
                                                                                  "                    <property name=\"can_focus\">False</property>\n"
                                                                                  "                    <property name=\"label\" translatable=\"yes\">monitor y position</property>\n"
                                                                                  "                  </object>\n"
                                                                                  "                  <packing>\n"
                                                                                  "                    <property name=\"expand\">False</property>\n"
                                                                                  "                    <property name=\"fill\">True</property>\n"
                                                                                  "                    <property name=\"position\">0</property>\n"
                                                                                  "                  </packing>\n"
                                                                                  "                </child>\n"
                                                                                  "                <child>\n"
                                                                                  "                  <object class=\"GtkBox\" id=\"box4\">\n"
                                                                                  "                    <property name=\"visible\">True</property>\n"
                                                                                  "                    <property name=\"can_focus\">False</property>\n"
                                                                                  "                    <child>\n"
                                                                                  "                      <object class=\"GtkScale\" id=\"y_monitors\">\n"
                                                                                  "                        <property name=\"visible\">True</property>\n"
                                                                                  "                        <property name=\"can_focus\">True</property>\n"
                                                                                  "                        <property name=\"draw_value\">False</property>\n"
                                                                                  "                      </object>\n"
                                                                                  "                      <packing>\n"
                                                                                  "                        <property name=\"expand\">True</property>\n"
                                                                                  "                        <property name=\"fill\">True</property>\n"
                                                                                  "                        <property name=\"position\">1</property>\n"
                                                                                  "                      </packing>\n"
                                                                                  "                    </child>\n"
                                                                                  "                    <child>\n"
                                                                                  "                      <object class=\"GtkSpinButton\" id=\"y_monitors_spin_button\">\n"
                                                                                  "                        <property name=\"visible\">True</property>\n"
                                                                                  "                        <property name=\"can_focus\">True</property>\n"
                                                                                  "                        <property name=\"text\" translatable=\"yes\">0,0000000000</property>\n"
                                                                                  "                        <property name=\"climb_rate\">0.01</property>\n"
                                                                                  "                        <property name=\"digits\">10</property>\n"
                                                                                  "                      </object>\n"
                                                                                  "                      <packing>\n"
                                                                                  "                        <property name=\"expand\">False</property>\n"
                                                                                  "                        <property name=\"fill\">True</property>\n"
                                                                                  "                        <property name=\"position\">2</property>\n"
                                                                                  "                      </packing>\n"
                                                                                  "                    </child>\n"
                                                                                  "                  </object>\n"
                                                                                  "                  <packing>\n"
                                                                                  "                    <property name=\"expand\">False</property>\n"
                                                                                  "                    <property name=\"fill\">True</property>\n"
                                                                                  "                    <property name=\"position\">1</property>\n"
                                                                                  "                  </packing>\n"
                                                                                  "                </child>\n"
                                                                                  "              </object>\n"
                                                                                  "              <packing>\n"
                                                                                  "                <property name=\"expand\">False</property>\n"
                                                                                  "                <property name=\"fill\">True</property>\n"
                                                                                  "                <property name=\"position\">9</property>\n"
                                                                                  "              </packing>\n"
                                                                                  "            </child>\n"
                                                                                  "          </object>\n"
                                                                                  "          <packing>\n"
                                                                                  "            <property name=\"resize\">False</property>\n"
                                                                                  "            <property name=\"shrink\">False</property>\n"
                                                                                  "          </packing>\n"
                                                                                  "        </child>\n"
                                                                                  "        <child>\n"
                                                                                  "          <placeholder/>\n"
                                                                                  "        </child>\n"
                                                                                  "      </object>\n"
                                                                                  "    </child>\n"
                                                                                  "  </object>\n"
                                                                                  "</interface>");

    Control control;
    Gtk::Window *win = control.init(builder);

    return app->run(*win);
}